---
- name: Install ferm packages
  apt:
    state: present
    update_cache: yes
    cache_valid_time: 60
    pkg:
      - ferm
  tags:
    - ferm
    - ferm-install
    - never
  notify:
    - ferm-restart
 #- name: Configure ferm service
 #  template: src={{ item.src }} dest=/etc/ferm/{{ item.dest }} mode={{ item.mode }}
 #  with_items:
 #    - { src: ferm.conf.j2, dest: ferm.conf, mode: 644 }
- name: Configure ferm service
  copy: 
    src: "{{ role_path }}/files/ferm.conf"
    dest: /etc/ferm/ferm.conf
    mode: '0644'
  tags:
    - ferm
    - ferm-conf
    - conf
  notify:
    - ferm-restart
